### ISSUE TITLE
C#/SDL2/emscripten question

### ISSUE THREAD

**Issue by ArnaudValensi** [yowl/wasmsdl#1]
Hi @yowl,

Thanks for this repository (and your work on dotnet).
I'm trying to build a C#/SDL2 project for the web. Would you still use this technique now, or is there a simpler way with net8 and the new native AOT feature?

I'm trying to follow this guide:
https://github.com/dotnet/runtimelab/blob/feature/NativeAOT-LLVM/docs/using-nativeaot/compiling.md#webassembly
but I'm not sure how to tell emscripten to include SDL2 when building.

Are you aware of some resources I can refer to?

Here is my project, for context: https://github.com/ArnaudValensi/net8-sdl2

**Comment by yowl** [comment]
I wouldn't use the mini runtime which is https://github.com/MichalStrehovsky/zerosharp.  It was just to see how small it could go at the time.   SDL2 is included via the project file 

https://github.com/yowl/wasmsdl/blob/713eb8694c306966deb5d6cfd92c286a946d3018/wasmsdl.csproj#L29

Otherwise I think the approach should still be valid.  net8 and Native AOT is what this uses .  CoreRT was renamed to NativeAOT.

**Comment by ArnaudValensi** [comment]
Thank you, I'll try this.

**Comment by ArnaudValensi** [comment]
It works, thanks!
